name: mlflow-env  # Optional (matches your environment name)
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - scikit-learn
  - pandas
  - numpy
  - pip:
    - mlflow>=2.0